language: java

branhes:
    only:
    - development
    - master

sudo: required

before install:
    - sudo apt update
 
install:
    - sudo apt install maven -y

script:
    - mvn clean package
    
after_success:
    - echo "Process terminated successfully"
    


